"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import vibeProspectingLogo from "@/assets/images/vibe-prospecting-logo.png";
import AgentsSidebar, { AgentDef } from "@/components/agents/AgentsSidebar";
import DownloadButtons from "@/components/agents/DownloadButtons";
import MiniTerminal, { MiniTerminalLine } from "@/components/common/MiniTerminal";
import { useAppSelector } from "@/redux/hooks";
import { toast } from "@/components/snakbar";
import {
  streamVibeProspectingAgent,
  VibeAgentJobSummary,
  VibeAgentProjectContext,
  VibeAgentStreamEvent,
  VibeAgentTemplate,
} from "@/lib/api/vibeProspectingAgentStream";
import { useLandingTheme } from "@/components/landingPage/landingTheme";
import type { LandingThemeTokens } from "@/components/landingPage/landingTheme";

interface ChatBubble {
  role: "user" | "assistant";
  text: string;
  downloadUrl?: string;
  rowCount?: number;
}

const AGENTS: AgentDef[] = [
  {
    id: "vibe_prospecting",
    name: "Vibe Prospecting",
    description: "B2B lead search & export",
    logo: vibeProspectingLogo,
  },
];

// Only "step" events feed the activity line — "message" events are skipped
// on purpose (see vibeProspectingAgentStream.ts's header comment): the
// lambda sends the same text via "message" and via the final "result"
// event's `reply` field except on cancel/export, so rendering chat bubbles
// off "result" alone avoids ever double-adding the same reply.
function eventToLine(event: VibeAgentStreamEvent): MiniTerminalLine | null {
  if (event.type !== "step") return null;
  const status: MiniTerminalLine["status"] =
    event.status === "completed" ? "done" : event.status === "failed" ? "error" : "active";
  return { text: event.error ? `${event.label}: ${event.error}` : event.label, status };
}

const SendIcon = () => (
  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <line x1="22" y1="2" x2="11" y2="13" />
    <polygon points="22 2 15 22 11 13 2 9 22 2" />
  </svg>
);

export default function AgentsPage() {
  const { t } = useLandingTheme();
  const accessToken = useAppSelector((state) => state.auth.tokens.accessToken);
  const project = useAppSelector((state) => state.auth.project);
  const projectId = project?.project_id ?? null;

  const [selectedAgentId, setSelectedAgentId] = useState(AGENTS[0].id);
  const [projectContext, setProjectContext] = useState<VibeAgentProjectContext | null>(null);
  const [templates, setTemplates] = useState<VibeAgentTemplate[]>([]);
  const [isLoadingWelcome, setIsLoadingWelcome] = useState(false);

  const [jobs, setJobs] = useState<VibeAgentJobSummary[]>([]);
  const [isLoadingJobs, setIsLoadingJobs] = useState(false);

  const [jobId, setJobId] = useState<string | null>(null);
  const [messages, setMessages] = useState<ChatBubble[]>([]);
  const [isSending, setIsSending] = useState(false);
  const [activityLine, setActivityLine] = useState<MiniTerminalLine | null>(null);
  const [input, setInput] = useState("");

  // A currently-valid presigned download URL for the open job, if any — only
  // ever set from a fresh export result in this session (get_job's s3_key
  // has no live URL attached, since presigned URLs expire after 1h and
  // aren't regenerated by that action). Drives the header DownloadButtons'
  // highlighted-vs-idle state.
  const [latestDownload, setLatestDownload] = useState<{ url: string; rowCount?: number } | null>(null);

  // Vibe Prospecting is deliberately single-use per project: once this
  // project has any REAL job (active or finished), "New chat" and the
  // template chips are disabled — starting a second, different search here
  // isn't allowed, the user has to switch to another project instead. This
  // is a frontend-only restriction; the backend's AGENT_TABLE schema
  // (project_id HASH / job_id RANGE) would technically allow more.
  //
  // "Real" excludes stage-0 jobs on purpose: the lambda's createJob() writes
  // a job row to DynamoDB immediately, before it ever checks whether Vibe
  // Prospecting is even connected for the project — so sending a message
  // before connecting the integration (a real, observed case) leaves behind
  // a permanent empty stub row (stage 0, no messages ever saved) that would
  // otherwise wrongly lock the project out of ever using the agent. A job
  // only reaches stage 1+ once it actually completed a real step, so
  // filtering on that is a reliable "did this job ever do anything" signal
  // available straight from list_jobs's summary shape, no extra fetch
  // needed. This is a frontend-only fix — the backend still writes those
  // stub rows; they're just never surfaced or counted here.
  const realJobs = jobs.filter((j) => j.stage > 0);
  const hasAnyJob = realJobs.length > 0;
  // Once the open job's own status comes back as anything other than
  // "active" (export delivered, or cancelled), the conversation itself is
  // locked too — no more messages can be sent on it.
  const [jobFinished, setJobFinished] = useState(false);

  const scrollRef = useRef<HTMLDivElement>(null);

  const loadJobs = async (pid: string): Promise<VibeAgentJobSummary[]> => {
    if (!accessToken) return [];
    setIsLoadingJobs(true);
    let list: VibeAgentJobSummary[] = [];
    try {
      await streamVibeProspectingAgent(accessToken, { action: "list_jobs", project_id: pid }, (event) => {
        if (event.type === "result" && event.statusCode === 200 && event.jobs) list = event.jobs;
      });
    } catch (err) {
      console.error("Failed to load agent jobs:", err);
    } finally {
      setIsLoadingJobs(false);
    }
    setJobs(list);
    return list;
  };

  const handleSelectJob = async (id: string) => {
    if (!accessToken || !projectId || isSending) return;
    setIsSending(true);
    setActivityLine(null);
    setLatestDownload(null);
    try {
      await streamVibeProspectingAgent(accessToken, { action: "get_job", project_id: projectId, job_id: id }, (event) => {
        const line = eventToLine(event);
        if (line) setActivityLine(line);
        if (event.type !== "result") return;
        if (event.statusCode === 200 && event.messages) {
          setJobId(id);
          setJobFinished(event.status !== "active");
          setMessages(
            event.messages.map((m) => ({
              role: m.role,
              text: m.text,
            }))
          );
          if (event.s3_key) {
            setMessages((prev) => [
              ...prev,
              { role: "assistant", text: "This conversation's export link has expired — ask me to run it again for a fresh download." },
            ]);
          }
        } else {
          toast.error(event.details?.join(" ") || event.error || "Couldn't load that conversation.");
        }
      });
    } catch (err) {
      console.error("Failed to load agent job:", err);
      toast.error("Couldn't load that conversation.");
    } finally {
      setIsSending(false);
      setActivityLine(null);
    }
  };

  // Loads project context + suggestion templates and the job history fresh
  // any time the active project changes — a different project has an
  // entirely different job history (AGENT_TABLE is keyed by project_id) and
  // its own ICP/competitors to personalize templates from. If this project
  // already has a job (single-use-per-project rule above), it's loaded
  // automatically instead of showing the empty welcome/template screen.
  useEffect(() => {
    if (!accessToken || !projectId) return;
    let cancelled = false;
    setJobId(null);
    setMessages([]);
    setLatestDownload(null);
    setJobFinished(false);
    (async () => {
      setIsLoadingWelcome(true);
      try {
        await streamVibeProspectingAgent(accessToken, { action: "welcome", project_id: projectId }, (event) => {
          if (cancelled) return;
          if (event.type === "result") {
            if (event.statusCode === 200) {
              setProjectContext(event.project_context ?? null);
              setTemplates(event.templates ?? []);
            } else {
              toast.error(event.details?.join(" ") || event.error || "Couldn't load the agent.");
            }
          }
        });
      } catch (err) {
        console.error("Failed to load Vibe Prospecting welcome context:", err);
        toast.error("Couldn't reach the Vibe Prospecting agent.");
      } finally {
        if (!cancelled) setIsLoadingWelcome(false);
      }
    })();
    (async () => {
      const list = await loadJobs(projectId);
      const real = list.filter((j) => j.stage > 0);
      if (!cancelled && real.length > 0) await handleSelectJob(real[0].job_id);
    })();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accessToken, projectId]);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, isSending]);

  const handleNewChat = () => {
    if (hasAnyJob) return;
    setJobId(null);
    setMessages([]);
    setActivityLine(null);
    setLatestDownload(null);
    setJobFinished(false);
  };

  const handleSend = async (text: string) => {
    if (!accessToken || !projectId || isSending || !text.trim() || jobFinished) return;
    const trimmed = text.trim();
    setInput("");
    setMessages((prev) => [...prev, { role: "user", text: trimmed }]);
    setIsSending(true);
    setActivityLine(null);
    try {
      await streamVibeProspectingAgent(
        accessToken,
        { action: "chat", project_id: projectId, job_id: jobId ?? undefined, message: trimmed },
        (event) => {
          const line = eventToLine(event);
          if (line) setActivityLine(line);
          if (event.type !== "result") return;
          if (event.statusCode !== 200) {
            toast.error(event.details?.join(" ") || event.error || "The agent couldn't process that.");
            return;
          }
          if (event.job_id) setJobId(event.job_id);
          if (event.download_url) {
            setMessages((prev) => [
              ...prev,
              { role: "assistant", text: `Exported ${event.row_count ?? 0} rows.`, downloadUrl: event.download_url, rowCount: event.row_count },
            ]);
            setLatestDownload({ url: event.download_url, rowCount: event.row_count });
            setJobFinished(true);
            toast.success(`Export ready — ${event.row_count ?? 0} rows.`);
          } else if (event.reply) {
            setMessages((prev) => [...prev, { role: "assistant", text: event.reply as string }]);
          }
          loadJobs(projectId);
        }
      );
    } catch (err) {
      console.error("Vibe Prospecting chat failed:", err);
      toast.error(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setIsSending(false);
    }
  };

  const handleRunTemplate = async (template: VibeAgentTemplate) => {
    if (!accessToken || !projectId || isSending || hasAnyJob) return;
    setJobId(null);
    setMessages([{ role: "user", text: template.prompt }]);
    setIsSending(true);
    setActivityLine(null);
    try {
      await streamVibeProspectingAgent(
        accessToken,
        { action: "run_template", project_id: projectId, template_id: template.id },
        (event) => {
          const line = eventToLine(event);
          if (line) setActivityLine(line);
          if (event.type !== "result") return;
          if (event.statusCode !== 200) {
            toast.error(event.details?.join(" ") || event.error || "That template couldn't be run.");
            return;
          }
          if (event.job_id) setJobId(event.job_id);
          if (event.download_url) {
            setMessages((prev) => [
              ...prev,
              { role: "assistant", text: `Exported ${event.row_count ?? 0} rows.`, downloadUrl: event.download_url, rowCount: event.row_count },
            ]);
            setLatestDownload({ url: event.download_url, rowCount: event.row_count });
            setJobFinished(true);
            toast.success(`Export ready — ${event.row_count ?? 0} rows.`);
          }
          loadJobs(projectId);
        }
      );
    } catch (err) {
      console.error("Vibe Prospecting template run failed:", err);
      toast.error(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setIsSending(false);
    }
  };

  const activeAgent = AGENTS.find((a) => a.id === selectedAgentId) ?? AGENTS[0];
  const hasConversation = messages.length > 0;
  const newChatDisabledReason = "Vibe Prospecting can only run once per project — switch to a different project to start a new search.";

  const cardStyle: React.CSSProperties = { border: `1px solid ${t.border}`, background: t.card };

  return (
    <div className="h-screen flex flex-col pt-20 md:pt-[88px] lg:pt-[104px] p-4 md:p-6 gap-4" style={{ color: t.fg }}>
      <div className="flex-1 min-h-0 flex gap-4">
        <AgentsSidebar
          agents={AGENTS}
          selectedAgentId={selectedAgentId}
          onSelectAgent={setSelectedAgentId}
          jobs={realJobs}
          isLoadingJobs={isLoadingJobs}
          activeJobId={jobId}
          onSelectJob={handleSelectJob}
          onNewChat={handleNewChat}
          agentsInUse={hasAnyJob ? [activeAgent.id] : []}
          newChatDisabled={hasAnyJob}
          newChatDisabledReason={newChatDisabledReason}
        />

        <section className="flex-1 min-w-0 rounded-3xl flex flex-col overflow-hidden" style={cardStyle}>
          {!projectId ? (
            <div className="flex-1 flex items-center justify-center px-6">
              <p className="text-sm" style={{ color: t.fgMid }}>Select or create a project first to use agents.</p>
            </div>
          ) : !hasConversation ? (
            <div className="flex-1 min-h-0 overflow-y-auto flex flex-col items-center justify-center px-6">
              <div className="w-14 h-14 rounded-2xl bg-white flex items-center justify-center overflow-hidden mb-4">
                <Image src={activeAgent.logo} alt="" width={34} height={34} className="object-contain" />
              </div>
              <h1 className="text-lg font-semibold mb-1.5" style={{ color: t.fg }}>{activeAgent.name}</h1>
              <p className="text-xs text-center max-w-md mb-6 leading-relaxed" style={{ color: t.fgMid }}>
                {isLoadingWelcome
                  ? "Loading your project context…"
                  : hasAnyJob
                  ? newChatDisabledReason
                  : `Search, enrich, and export B2B leads matching ${projectContext?.project_name ?? "your project"}'s ICP.`}
              </p>

              {templates.length > 0 && !hasAnyJob && (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 w-full max-w-xl mb-6">
                  {templates.map((tpl) => (
                    <button
                      key={tpl.id}
                      onClick={() => handleRunTemplate(tpl)}
                      disabled={isSending}
                      className="text-left px-3.5 py-3 text-xs font-medium rounded-xl transition-colors disabled:opacity-50"
                      style={{ color: t.fgMid, background: t.surface, border: `1px solid ${t.border}` }}
                    >
                      {tpl.label}
                    </button>
                  ))}
                </div>
              )}

              {!hasAnyJob && (
                <div className="w-full max-w-xl">
                  <ChatInput value={input} onChange={setInput} onSend={handleSend} disabled={isSending} t={t} />
                  {(isSending || activityLine) && (
                    <div className="mt-2.5">
                      <MiniTerminal line={activityLine} idleLabel="Working…" />
                    </div>
                  )}
                </div>
              )}
            </div>
          ) : (
            <>
              <div className="flex-none flex items-center justify-between px-5 py-3.5" style={{ borderBottom: `1px solid ${t.border}` }}>
                <div className="flex items-center gap-2 min-w-0">
                  <div className="w-6 h-6 rounded-md bg-white flex items-center justify-center overflow-hidden flex-none">
                    <Image src={activeAgent.logo} alt="" width={15} height={15} className="object-contain" />
                  </div>
                  <p className="text-xs font-semibold truncate" style={{ color: t.fg }}>{activeAgent.name}</p>
                </div>
                <DownloadButtons downloadUrl={latestDownload?.url} rowCount={latestDownload?.rowCount} />
              </div>

              <div ref={scrollRef} className="flex-1 min-h-0 overflow-y-auto px-5 py-5 space-y-4">
                {messages.map((m, i) => (
                  <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>
                    <div
                      className="max-w-[80%] rounded-2xl px-4 py-2.5 text-[13px] leading-relaxed whitespace-pre-wrap"
                      style={
                        m.role === "user"
                          ? { background: t.gold, color: t.isDark ? "#0a0a0a" : "#faf8f4" }
                          : { background: t.surface, border: `1px solid ${t.border}`, color: t.fg }
                      }
                    >
                      {m.text}
                      {m.downloadUrl && (
                        <div className="mt-2.5">
                          <DownloadButtons downloadUrl={m.downloadUrl} rowCount={m.rowCount} variant="subtle" />
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>

              <div className="flex-none px-5 pb-5 pt-1">
                {jobFinished && (
                  <p className="text-[11px] mb-2 leading-relaxed" style={{ color: t.fgMid }}>{newChatDisabledReason}</p>
                )}
                <ChatInput value={input} onChange={setInput} onSend={handleSend} disabled={isSending || jobFinished} t={t} />
                {(isSending || activityLine) && (
                  <div className="mt-2.5">
                    <MiniTerminal line={activityLine} idleLabel="Working…" />
                  </div>
                )}
              </div>
            </>
          )}
        </section>
      </div>
    </div>
  );
}

interface ChatInputProps {
  value: string;
  onChange: (v: string) => void;
  onSend: (text: string) => void;
  disabled: boolean;
  t: LandingThemeTokens;
}

function ChatInput({ value, onChange, onSend, disabled, t }: ChatInputProps) {
  return (
    <div
      className="flex items-end gap-2 rounded-2xl px-3.5 py-2.5 transition-colors"
      style={{ background: t.surface, border: `1px solid ${t.border}` }}
    >
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter" && !e.shiftKey) {
            e.preventDefault();
            onSend(value);
          }
        }}
        placeholder="Ask for the leads you're looking for…"
        rows={1}
        className="flex-1 resize-none bg-transparent text-[13px] focus:outline-none max-h-32"
        style={{ color: t.fg }}
      />
      <button
        onClick={() => onSend(value)}
        disabled={disabled || !value.trim()}
        aria-label="Send"
        className="flex-none w-8 h-8 flex items-center justify-center rounded-lg hover:brightness-110 transition-all disabled:opacity-40"
        style={{ background: t.gold, color: t.isDark ? "#0a0a0a" : "#faf8f4" }}
      >
        <SendIcon />
      </button>
    </div>
  );
}
